name: Check compile, tests & javadocs
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - 3.0.0-dev # This will be moved to master once released, master taking a "legacy/v2"
    paths:
      - 'pom.xml'
      - 'src/main/**.java'
      - 'src/test/**.java'
      - 'src/main/**.kt'
      - 'src/test/**.kt'
  push:
    branches: 
      - master
      - 3.0.0-dev
    paths: 
      - 'pom.xml'
      - 'src/main/**.java'
      - 'src/test/**.java'
      - 'src/main/**.kt'
      - 'src/test/**.kt'
jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Compile and run tests with Maven
        run: mvn -B --file pom.xml test
  check-javadoc:
    runs-on: ubuntu-latest
    if: env.GITHUB_REF_NAME == 'master'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Compile and Build Javadocs with Maven
        run: mvn -P check-docs -B javadoc:javadoc --file pom.xml
  check-kdocs:
    runs-on: ubuntu-latest
    if: env.GITHUB_REF_NAME == '3.0.0-dev'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build KDocs with Maven
        run: mvn -P docs -B dokka:dokka --file pom.xml
